### ISSUE TITLE
After place the bbb tiny block in the server, the server crashed

### ISSUE THREAD

**Issue by UnnamedWei** [starfish-studios/Building-But-Better#2]
[crash-2024-05-28_07.47.41-server.txt](https://github.com/starfish-studios/Building-But-Better/files/15462614/crash-2024-05-28_07.47.41-server.txt)

**Comment by ActaMonVerba** [comment]
Same here.
[logs.panel.gg_5474a62bf0cce4a6b2635fa79ad669bf.pdf](https://github.com/starfish-studios/Building-But-Better/files/15462631/logs.panel.gg_5474a62bf0cce4a6b2635fa79ad669bf.pdf)

**Comment by crispytwig** [comment]
Hello! Thank you for reporting this. I worked with another community member on Discord _(shoutout to goatscape for being my guinea pig)_ to resolve this. 1.0.2 should fix this, but please let me know if the issue persists! @ActaMonVerba @UnnamedWei 

The file is available immediately on Modrinth and is pending on CurseForge.
https://modrinth.com/mod/building-but-better/version/1.0.2-fabric-1.20.1
